//go:build authz

package authz

import (
	"fmt"
	"os"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
)

// writeReport renders tests/authz/MATRIX.md from the run: the endpoint ×
// result evidence table feeding the QA report. Key material is masked; only
// the summary and per-probe results are written.
func writeReport(t *testing.T, s *stack, l *ledger) {
	t.Helper()

	path := os.Getenv("ORVEXA_AUTHZ_REPORT")
	if path == "" {
		path = "MATRIX.md"
	}

	var pass, passSecured, passDegraded, defectRows, conditional, failed int
	for _, r := range l.rows {
		switch r.Result {
		case "PASS":
			pass++
		case "PASS-SECURED":
			passSecured++
		case "PASS-DEGRADED":
			passDegraded++
		case "DEFECT":
			defectRows++
		case "CONDITIONAL":
			conditional++
		default:
			failed++
		}
	}
	hard := l.hardFails()

	var b strings.Builder
	fmt.Fprintf(&b, "# Orvexa Tenancy & Authorization Matrix — run evidence (#40)\n\n")
	fmt.Fprintf(&b, "_Generated by `tests/authz` (TestAuthzMatrix). Do not edit by hand — re-run the harness._\n\n")

	b.WriteString("## Run environment\n\n")
	fmt.Fprintf(&b, "| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| Run started (UTC) | %s |\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "| Repo commit | %s |\n", s.gitRev)
	fmt.Fprintf(&b, "| Go | %s |\n", runtime.Version())
	fmt.Fprintf(&b, "| PostgreSQL | devstack (`scripts/devstack.sh`, port %s), migrations applied |\n", devstackPortLabel())
	fmt.Fprintf(&b, "| API process | `go run ./cmd/api` on %s (ORVEXA_* env; simulator comms, inproc bus, API-key-only auth, search degraded) |\n", s.base)
	fmt.Fprintf(&b, "| Tenants | 2 minted per the documented bootstrap path (operations.md § First tenant bootstrap — SQL, hashed keys, scope `{api}`); A=`%s`, B=`%s` |\n", short(s.fx.tenantA), short(s.fx.tenantB))
	fmt.Fprintf(&b, "| Credentials | key A `%s`, key B `%s` (masked; minted at runtime, never committed) |\n", maskKey(s.fx.keyA), maskKey(s.fx.keyB))
	fmt.Fprintf(&b, "| Invocation | `scripts/devstack.sh start && go test -race -tags=authz ./tests/authz/` |\n\n")

	b.WriteString("## Result summary\n\n")
	fmt.Fprintf(&b, "| Probes | PASS | PASS (degraded) | PASS (secured) | DEFECT rows | Conditional | FAIL | Hard assertion failures |\n")
	fmt.Fprintf(&b, "|---|---|---|---|---|---|---|---|\n")
	fmt.Fprintf(&b, "| %d | %d | %d | %d | %d | %d | %d | %d |\n\n",
		len(l.rows), pass, passDegraded, passSecured, defectRows, conditional, failed, hard)

	b.WriteString("## Legend\n\n")
	b.WriteString("- **PASS** — hard-asserted invariant held (status + no tenant-A identifier leakage).\n")
	b.WriteString("- **PASS (degraded)** — authenticated and correctly tenant-scoped; the route serves its typed degradation (search 503 `search.not_configured` with OpenSearch off).\n")
	b.WriteString("- **PASS (secured)** — a previously recorded defect now returns the secure status (fix verified by re-run).\n")
	b.WriteString("- **DEFECT** — cross-tenant behavior recorded as a filed `type/bug` issue. Rows accept ONLY the recorded defect status or the secured status; anything else is a FAIL. Defects are never fixed in this package.\n")
	b.WriteString("- **Conditional** — surface not mounted in this run by design (identity plane disabled: no `ORVEXA_OIDC_*`), probed to prove fail-closed absence (404).\n\n")

	b.WriteString("## Endpoint × result matrix (v1 route tree from `internal/httpserver/v1.go`)\n\n")
	b.WriteString("| Route | no-auth | tenant-B key (foreign) | tenant-A key (own) | Verdict | Notes |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, r := range routeOrder(l) {
		fmt.Fprintf(&b, "| **%s**<br>`%s`<br><sub>%s</sub>", r.RouteID, r.Route, r.Mount)
		for _, slot := range []string{"no-auth", "foreign", "own"} {
			row := l.byID[r.RouteID+"|"+slot]
			if row == nil {
				fmt.Fprintf(&b, "| — ")
				continue
			}
			fmt.Fprintf(&b, "| %s → **%s** ", row.Expect, row.Result)
		}
		fmt.Fprintf(&b, "| %s |\n", routeVerdict(l, r.RouteID))
	}
	b.WriteString("\n")

	b.WriteString("## Extra probes\n\n")
	b.WriteString("| ID | Route | Probe | Expect | Got | Result | Note |\n|---|---|---|---|---|---|---|\n")
	for _, r := range l.rows {
		switch r.RouteID {
		case "PLAT-1", "PLAT-2", "AUTH-1", "AUTH-2", "WEB-1", "WEB-2", "WEB-3", "WEB-4", "ID-1", "ID-2",
			"IDW-1", "IDW-2", "IDW-3", "ORACLE-1", "ORACLE-2":
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %d | **%s** | %s |\n",
				r.RouteID, r.Route, r.Probe, r.Expect, r.Got, r.Result, r.Note)
		}
	}
	b.WriteString("\n")

	b.WriteString("## Cross-tenant reference-in-body probes (defect ratchet rows)\n\n")
	b.WriteString("| ID | Route | Probe | Expected | Got | Result | Defect |\n|---|---|---|---|---|---|---|\n")
	for _, r := range l.rows {
		if strings.HasPrefix(r.RouteID, "REF-") || r.RouteID == "R24" || r.RouteID == "R26" || r.RouteID == "R30" {
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %d | **%s** | %s |\n",
				r.RouteID, r.Route, r.Probe, r.Expect, r.Got, r.Result, defectRef(r.Note))
		}
	}
	b.WriteString("\n")

	b.WriteString("## Filed isolation defects\n\n")
	for _, d := range defectRegistry {
		observed := "not observed this run"
		if st, ok := l.defect[d.id]; ok && st != 0 {
			observed = fmt.Sprintf("reproduced this run (HTTP %d)", st)
		}
		fmt.Fprintf(&b, "### %s — %s `%s` (%s)\n\n", d.id, d.issue, d.owner, observed)
		fmt.Fprintf(&b, "%s\n\nRepro: %s\n\n", d.title, d.repro)
	}

	b.WriteString("## Notes & scope\n\n")
	b.WriteString("- **100% route accounting:** every registration in `MountV1` (v1.go) is probed above — customers, conversations, interactions, agents, queues, cases, calls, messages, routing (+presence), AI, workflows, analytics, search — plus the public webhook ingress, the authenticated index, platform health endpoints and the conditional identity surface.\n")
	b.WriteString("- **Search degradation:** the route is mounted and authenticated in every deployment; in this devstack run OpenSearch is off, so the honest typed `503 search.not_configured` is the correct success signal. When OpenSearch is configured the tenant filter is derived server-side from the authenticated principal (no tenant parameter exists on the wire).\n")
	b.WriteString("- **Webhook ingress** is public by design (providers cannot hold API keys): the evidence rows prove signature fail-closed behavior, including that API keys confer nothing there.\n")
	b.WriteString("- **Capability RBAC** (migration 0012 / [O-29]) is exercised for API-key principals via the mounted capability middleware (scope `{api}` passes; tenant-B tool calls are policy-refused 403 on a foreign AI agent).\n")
	b.WriteString("- **Defect policy (issue #40):** failures are NOT fixed in this package. Each DEFECT row has a filed `type/bug` issue (section above); the ratchet rows keep the suite green only while the platform behaves exactly as recorded, and auto-re-verify once a fix lands.\n")
	b.WriteString("- No credential material is committed: keys are minted per run and masked in this report; the webhook HMAC secret is a fixed test fixture.\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write report %s: %v", path, err)
	}
	t.Logf("authz matrix report written to %s (%d probes, %d hard failures)", path, len(l.rows), hard)
}

// routeOrder returns one anchor row per route id, preserving probe order.
func routeOrder(l *ledger) []*mrow {
	seen := map[string]bool{}
	var out []*mrow
	for _, r := range l.rows {
		switch r.RouteID {
		case "PLAT-1", "PLAT-2", "AUTH-1", "AUTH-2", "WEB-1", "WEB-2", "WEB-3", "WEB-4", "ID-1", "ID-2",
			"IDW-1", "IDW-2", "IDW-3", "ORACLE-1", "ORACLE-2":
			continue
		}
		if strings.HasPrefix(r.RouteID, "REF-") {
			continue
		}
		if !seen[r.RouteID] {
			seen[r.RouteID] = true
			out = append(out, r)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].RouteID < out[j].RouteID })
	return out
}

// routeVerdict summarizes all rows of a route id.
func routeVerdict(l *ledger, routeID string) string {
	verdict := "PASS"
	for _, r := range l.rows {
		if r.RouteID != routeID {
			continue
		}
		switch {
		case r.Result == "FAIL":
			return "**FAIL**"
		case r.Result == "DEFECT":
			verdict = "PASS with DEFECT (" + defectRef(r.Note) + ")"
		}
	}
	return verdict
}

func defectRef(note string) string {
	if strings.HasPrefix(note, "D") && len(note) >= 2 {
		if d := defectByID(note[:2]); d != nil {
			return d.issue + " (" + d.id + ")"
		}
	}
	return "—"
}

func devstackPortLabel() string {
	if p := os.Getenv("ORVEXA_DEVSTACK_PORT"); p != "" {
		return p
	}
	return defaultDevstackPort
}

func short(id string) string {
	if len(id) <= 8 {
		return id
	}
	return id[:8] + "…"
}
